<% project_name = 'res-mgmt-system' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: res-mgmt-system_development

test:
  <<: *default
  database: res-mgmt-system_test
